{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ontele.component" (dict "root" . "name" "promtail") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ontele.componentLabels" (dict "root" . "component" "promtail") | nindent 4 }}
{{- if .Values.promtail.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ontele.component" (dict "root" . "name" "promtail") }}-{{ .Release.Namespace }}
  labels:
    {{- include "ontele.componentLabels" (dict "root" . "component" "promtail") | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ontele.component" (dict "root" . "name" "promtail") }}-{{ .Release.Namespace }}
  labels:
    {{- include "ontele.componentLabels" (dict "root" . "component" "promtail") | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ontele.component" (dict "root" . "name" "promtail") }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "ontele.component" (dict "root" . "name" "promtail") }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
