{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ontele.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ontele.componentLabels" (dict "root" . "component" "server") | nindent 4 }}
type: Opaque
stringData:
  {{- if or .Values.postgresql.enabled .Values.externalDatabase.url }}
  DATABASE_URL: {{ include "ontele.databaseUrl" . | quote }}
  {{- end }}
  ONTELE_TMDB_API_KEY: {{ .Values.config.tmdbApiKey | quote }}
{{- end }}
