# SPDX-License-Identifier: Apache-2.0
# Copy to 11-secrets.yaml (git-ignored) and fill in, or create with:
#   kubectl -n ontele create secret generic ontele-secrets \
#     --from-literal=POSTGRES_PASSWORD=... --from-literal=DATABASE_URL=postgres://ontele:...@postgres:5432/ontele \
#     --from-literal=ONTELE_TMDB_API_KEY=...
#   kubectl -n ontele create secret generic oauth2-proxy \
#     --from-literal=OAUTH2_PROXY_CLIENT_ID=... --from-literal=OAUTH2_PROXY_CLIENT_SECRET=... \
#     --from-literal=OAUTH2_PROXY_COOKIE_SECRET=$(python3 -c 'import os,base64; print(base64.urlsafe_b64encode(os.urandom(32)).decode())')
apiVersion: v1
kind: Secret
metadata:
  name: ontele-secrets
  namespace: ontele
type: Opaque
stringData:
  POSTGRES_USER: ontele
  POSTGRES_PASSWORD: change-me-please
  POSTGRES_DB: ontele
  DATABASE_URL: postgres://ontele:change-me-please@postgres:5432/ontele
  ONTELE_TMDB_API_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: ontele
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: ""
  OAUTH2_PROXY_CLIENT_SECRET: ""
  OAUTH2_PROXY_COOKIE_SECRET: "replace-with-32-byte-base64-secret"
