#!/usr/bin/env sh
# SPDX-License-Identifier: Apache-2.0
# Regenerates 15-observability-config.yaml from the files under deploy/
# (single source of truth shared with docker-compose). Requires kubectl.
set -eu
cd "$(dirname "$0")"
out=15-observability-config.yaml
{
  echo "# SPDX-License-Identifier: Apache-2.0"
  echo "# GENERATED by gen-configmaps.sh — edit the files under deploy/ instead."
  kubectl create configmap loki-config -n ontele --dry-run=client -o yaml --from-file=loki.yml=../loki/loki.yml
  echo "---"
  kubectl create configmap promtail-config -n ontele --dry-run=client -o yaml --from-file=promtail.yml=../promtail/promtail-k8s.yml
  echo "---"
  kubectl create configmap grafana-datasources -n ontele --dry-run=client -o yaml --from-file=datasources.yml=../grafana/provisioning/datasources/datasources.yml
  echo "---"
  kubectl create configmap grafana-dashboards-provider -n ontele --dry-run=client -o yaml --from-file=dashboards.yml=../grafana/provisioning/dashboards/dashboards.yml
  echo "---"
  kubectl create configmap grafana-dashboards -n ontele --dry-run=client -o yaml --from-file=ontele.json=../grafana/dashboards/ontele.json
} > "$out"
echo "wrote $out"

# keep the Helm chart's copies in sync (single source of truth under deploy/)
helm_files=../helm/ontele/files
cp ../loki/loki.yml "$helm_files/loki.yml"
cp ../promtail/promtail-k8s.yml "$helm_files/promtail.yml"
cp ../grafana/provisioning/datasources/datasources.yml "$helm_files/grafana-datasources.yml"
cp ../grafana/provisioning/dashboards/dashboards.yml "$helm_files/grafana-dashboards-provider.yml"
cp ../grafana/dashboards/ontele.json "$helm_files/dashboards/ontele.json"
echo "synced $helm_files"
