{{- if .Values.oauth2Proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ontele.component" (dict "root" . "name" "oauth2-proxy") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ontele.componentLabels" (dict "root" . "component" "oauth2-proxy") | nindent 4 }}
spec:
  replicas: {{ .Values.oauth2Proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "ontele.selectorLabels" (dict "root" . "component" "oauth2-proxy") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ontele.selectorLabels" (dict "root" . "component" "oauth2-proxy") | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/oauth2-proxy/configmap.yaml") . | sha256sum }}
    spec:
      {{- include "ontele.imagePullSecrets" . | nindent 6 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      containers:
        - name: oauth2-proxy
          image: "{{ .Values.oauth2Proxy.image.repository }}:{{ .Values.oauth2Proxy.image.tag }}"
          imagePullPolicy: {{ .Values.oauth2Proxy.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 4180
          envFrom:
            - configMapRef:
                name: {{ include "ontele.component" (dict "root" . "name" "oauth2-proxy") }}
            - secretRef:
                name: {{ include "ontele.oauth2Proxy.secretName" . }}
          {{- with .Values.oauth2Proxy.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            periodSeconds: 30
          resources:
            {{- toYaml .Values.oauth2Proxy.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
{{- end }}
