{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ontele.component" (dict "root" . "name" "grafana") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ontele.componentLabels" (dict "root" . "component" "grafana") | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- include "ontele.storageClassName" (dict "root" $ "local" .Values.grafana.persistence.storageClass) | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
